//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EkonomiService
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonalSchema
    {
        public int Id { get; set; }
        public string Måndag { get; set; }
        public string Tisdag { get; set; }
        public string Onsdag { get; set; }
        public string Torsdag { get; set; }
        public string Fredag { get; set; }
        public string Lördag { get; set; }
        public string Söndag { get; set; }
    }
}
